### PR TITLE
Calculate the utc offset from the time zone offset

### PR DESCRIPTION
**Pull request by andreax79**
I wrote this small patch for calculating the utc offset from the time zone offset

### CODE REVIEW

**Comment by amdt** [comment]
Thanks for the pull request!

This seems a bit complicated, but perhaps I'm missing something. Would you mind going into a little more detail as to how you chose to implement this?

What do you think about setting `g:sunset_utc_offset` like this?

```VimL
let g:sunset_utc_offset = strftime("%z")[:2]
```

**Comment by andreax79** [comment]
Hi, I got some problem in converting a string starting with 0 into a number. On my mac, strftime returns +0100, so if I try, e.g. echo 0100/100, it prints 0 (0100 is octal for vim :-( )

**Comment by amdt** [comment]
That's a good point. Vim considers strings starting with zeroes to be octal. We can use `str2nr()` to force the base:

```
str2nr( {expr} [, {base}])				*str2nr()*
		Convert string {expr} to a number.
		{base} is the conversion base, it can be 8, 10 or 16.
		When {base} is omitted base 10 is used.  This also means that
		a leading zero doesn't cause octal conversion to be used, as
		with the default String to Number conversion.
		When {base} is 16 a leading "0x" or "0X" is ignored.  With a
		different base the result will be zero.
		Text after the number is silently ignored.
```

How about this?

```VimL
let g:sunset_utc_offset = str2nr(strftime("%z")[:2])
```

**Comment by andreax79** [comment]
Perfect, I modified the patch using str2nr.

**Comment by amdt** [comment]
Merged into `develop` with c77e7f78bbfce5a600357093d84581b0afdfc34b.

I'll update the documentation and make a new release later in the week.

Thanks again for your pull request!

**Pull request closed without merging**
